import { AsyncFlow, AsyncNode } from "@fractal-solutions/qflow";
import { CodeInterpreterNode } from "@fractal-solutions/qflow/nodes";
import fs from "fs";
import path from "path";
import process from "process";
import Papa from "papaparse";

// This is a self-contained parser module for Zoho Tickets CSV data.
export function zoho_ticketsParserWorkflow() {
  const flow = new AsyncFlow();

  // 1. Node to read and process the CSV
  const processCsvNode = new AsyncNode();
  processCsvNode.execAsync = async (shared) => {
    const csvPath = path.join(shared.data_directory || 'data', 'zoho_tickets.csv');
    const clientName = shared.client_name;
    console.log(`Zoho Parser: Reading CSV from ${csvPath} for client: ${clientName}`);

    if (!fs.existsSync(csvPath)) {
      console.warn(`Zoho Parser: Could not find zoho_tickets.csv at ${csvPath}`);
      shared.output = { tickets: { source: 'Zoho', total: 0, software_count: 0, hardware_count: 0, misc_count: 0, chart_path: null } };
      return;
    }

    const file = fs.readFileSync(csvPath, 'utf8');
    // Skip header rows generated by Zoho
    const lines = file.split('\n');
    const csvData = lines.slice(4).join('\n');

    const parseResult = Papa.parse(csvData, { header: true });
    
    // Filter for the specific client
    const clientTickets = parseResult.data.filter(row => row['Account Name'] && row['Account Name'].trim() === clientName);

    // Classify tickets
    let hardware = 0;
    let software = 0;
    let misc = 0;

    const hardwareKeywords = ['laptop', 'pc', 'printer', 'disk', 'camera', 'microphone', 'inspiron', 'latitude', 'dymo', 'toner', 'mouse', 'keyboard', 'monitor', 'hdmi', 'dongle', 'server'];
    const softwareKeywords = ['windows', 'webroot', 'antivirus', 'outlook', 'quickbooks', 'office', 'm365', 'microsoft', 'adobe', 'vpn', 'hubspot', 'sharepoint', 'winqs', 'sunsystems'];

    for (const ticket of clientTickets) {
      const subject = (ticket.Subject || '').toLowerCase();
      if (hardwareKeywords.some(kw => subject.includes(kw))) {
        hardware++;
      } else if (softwareKeywords.some(kw => subject.includes(kw))) {
        software++;
      } else {
        misc++;
      }
    }
    
    console.log(`Zoho Parser: Found ${clientTickets.length} tickets. Hardware: ${hardware}, Software: ${software}, Misc: ${misc}`);

    // Store counts for the next node
    shared.ticket_counts = {
        Hardware: hardware,
        Software: software,
        Miscellaneous: misc
    };
    shared.total_tickets = clientTickets.length;
  };

  // 2. Node to generate the chart
  const generateChartNode = new CodeInterpreterNode();
  generateChartNode.setParams({
    interpreterPath: path.join(process.cwd(), "venv", "Scripts", "python.exe")
  });
  generateChartNode.prepAsync = async (shared) => {
    const counts = shared.ticket_counts;
    // Sanitize client name for filename
    const clientNameSanitized = shared.client_name.replace(/[^a-zA-Z0-9]/g, '_');
    const chartFileName = `zoho_tickets_${clientNameSanitized}.png`;
    const chartPathRelative = path.join('assets', chartFileName);
    
    // Ensure forward slashes for Python path string, as Python handles them universally
    const chartPathForPython = chartPathRelative.replace(/\\/g, '/'); 
    
    shared.chart_path = chartPathRelative; // Store relative path for JSON

    const pythonCode = `
import matplotlib.pyplot as plt
import os
import json # Used for safely converting JS arrays/objects to Python lists/dicts

# Python code now receives pre-processed data and path
categories = json.loads('${JSON.stringify(Object.keys(counts))}')
values = json.loads('${JSON.stringify(Object.values(counts))}')
chart_file_path = r"${chartPathForPython}" # Use raw string for Python path

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(categories, values, color=['#4E79A7', '#F28E2B', '#E15759'])

ax.set_ylabel('Number of Tickets')
ax.set_title('Monthly Ticket Summary by Category')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.yaxis.grid(True, linestyle='--', alpha=0.6)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 0.1, int(yval), ha='center', va='bottom')

# Ensure assets directory exists. os.path.dirname handles platform differences.
os.makedirs(os.path.dirname(chart_file_path), exist_ok=True)
plt.savefig(chart_file_path)
print(f"Chart saved to {chart_file_path}")
    `;
    generateChartNode.setParams({ code: pythonCode });
  };
  
  // 3. Node to format the final output
  const formatOutputNode = new AsyncNode();
  formatOutputNode.execAsync = async (shared) => {
    shared.output = {
      tickets: {
        source: 'Zoho',
        total: shared.total_tickets,
        software_count: shared.ticket_counts.Software,
        hardware_count: shared.ticket_counts.Hardware,
        misc_count: shared.ticket_counts.Miscellaneous,
        chart_path: shared.chart_path
      }
    };
    console.log("Zoho Parser: Completed and formatted output.");
  };

  // Chain the nodes
  flow.start(processCsvNode);
  processCsvNode.next(generateChartNode);
  generateChartNode.next(formatOutputNode);

  return flow;
}