import { AsyncFlow, AsyncNode } from "@fractal-solutions/qflow";
import { CodeInterpreterNode } from "@fractal-solutions/qflow/nodes";
import fs from "fs";
import path from "path";
import process from "process";
import Papa from "papaparse";

// This is a self-contained parser module for Zoho Tickets CSV data.
export function zoho_ticketsParserWorkflow() {
  const flow = new AsyncFlow();

  // 1. Node to read and process the CSV
  const processCsvNode = new AsyncNode();
  // Add prepAsync to ensure shared is passed correctly as prepRes to execAsync
  processCsvNode.prepAsync = async (shared) => {
    // Defensive check
    if (typeof shared === 'undefined' || shared === null) {
      console.warn("Zoho Parser: 'shared' object was undefined or null in processCsvNode.prepAsync, initializing to empty object.");
      shared = {};
    }
    return shared; // Propagate shared to execAsync via prepRes
  };

  processCsvNode.execAsync = async (prepRes) => { // Now receives prepRes, which is `shared`
    let shared = prepRes; // Alias for clarity
    // Defensive check (should ideally be handled by prepAsync)
    if (typeof shared === 'undefined' || shared === null) {
      console.warn("Zoho Parser: 'shared' object was undefined or null in processCsvNode.execAsync (after prepAsync), re-initializing.");
      shared = {};
    }

    const csvPath = path.join(shared.data_directory || 'data', 'zoho_tickets.csv');
    const clientName = shared.client_name;
    console.log(`Zoho Parser: Reading CSV from ${csvPath} for client: ${clientName}`);

    if (!shared.data_directory || !shared.client_name) {
        throw new Error("Zoho Parser: Missing data_directory or client_name in shared object for CSV processing.");
    }
    
    if (!fs.existsSync(csvPath)) {
      console.warn(`Zoho Parser: Could not find zoho_tickets.csv at ${csvPath}`);
      // On error, create an error file path
      const clientNameSanitized = shared.client_name.replace(/[^a-zA-Z0-9]/g, '_');
      const errorFilePath = path.join(process.cwd(), `temp_zoho_tickets_error_${clientNameSanitized}.json`);
      fs.writeFileSync(errorFilePath, JSON.stringify({ error: "Zoho tickets CSV file not found." }, null, 2));
      shared.output_filepath = errorFilePath;
      return shared; // Return shared to propagate the error file path
    }

    const file = fs.readFileSync(csvPath, 'utf8');
    // Skip header rows generated by Zoho
    const lines = file.split('\n');
    let headerStartIndex = 0; // Find header row dynamically
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].includes("Account Name")) {
            headerStartIndex = i;
            break;
        }
    }
    const csvData = lines.slice(headerStartIndex).join('\n');


    const parseResult = Papa.parse(csvData, { header: true, skipEmptyLines: true });
    
    // Filter for the specific client
    const clientTickets = parseResult.data.filter(row => row['Account Name'] && row['Account Name'].trim() === clientName);

    // Classify tickets
    let hardware = 0;
    let software = 0;
    let misc = 0;

    const hardwareKeywords = ['laptop', 'pc', 'printer', 'disk', 'camera', 'microphone', 'inspiron', 'latitude', 'dymo', 'toner', 'mouse', 'keyboard', 'monitor', 'hdmi', 'dongle', 'server', 'hardware'];
    const softwareKeywords = ['windows', 'webroot', 'antivirus', 'outlook', 'quickbooks', 'office', 'm365', 'microsoft', 'adobe', 'vpn', 'hubspot', 'sharepoint', 'winqs', 'sunsystems', 'software'];

    for (const ticket of clientTickets) {
      const subject = (ticket.Subject || '').toLowerCase();
      if (hardwareKeywords.some(kw => subject.includes(kw))) {
        hardware++;
      } else if (softwareKeywords.some(kw => subject.includes(kw))) {
        software++;
      } else {
        misc++;
      }
    }
    
    console.log(`Zoho Parser: Found ${clientTickets.length} tickets. Hardware: ${hardware}, Software: ${software}, Misc: ${misc}`);

    // Store counts on the shared object for the next node
    shared.ticket_counts = {
        Hardware: hardware,
        Software: software,
        Miscellaneous: misc
    };
    shared.total_tickets = clientTickets.length;
    return shared; // Return shared object
  };

  // 2. Node to generate the chart
  const generateChartNode = new CodeInterpreterNode();
  generateChartNode.setParams({
    interpreterPath: path.join(process.cwd(), "venv", "Scripts", "python.exe")
  });
  generateChartNode.prepAsync = async (shared) => { // prepAsync receives `shared`
    // Defensive check
    if (typeof shared === 'undefined' || shared === null) {
      console.warn("Zoho Parser: 'shared' object was undefined or null in generateChartNode.prepAsync, initializing.");
      shared = {};
    }
    if (!shared.ticket_counts) {
        throw new Error("Zoho Parser: Missing ticket_counts in shared object for chart generation.");
    }

    const counts = shared.ticket_counts;
    const clientNameSanitized = shared.client_name.replace(/[^a-zA-Z0-9]/g, '_');
    const chartFileName = `zoho_tickets_${clientNameSanitized}.png`;
    const chartPathRelative = path.join('assets', chartFileName);
    
    const chartPathForPython = chartPathRelative.replace(/\\/g, '/'); 
    
    shared.chart_path = chartPathRelative; // Store relative path for JSON

    const pythonCode = `
import matplotlib.pyplot as plt
import os
import json

categories = json.loads('${JSON.stringify(Object.keys(counts))}')
values = json.loads('${JSON.stringify(Object.values(counts))}')
chart_file_path = r"${chartPathForPython}"

PRIMARY = "#0047AB"
ACCENT = "#FF5733"
SURFACE = "#f4f4f4"
LIGHT = "#e6ecf5"
TEXT = "#222222"
MUTED = "#5b6878"

plt.rcParams["font.family"] = "DejaVu Sans"
plt.rcParams["axes.titlesize"] = 13
plt.rcParams["axes.labelsize"] = 10
plt.rcParams["xtick.labelsize"] = 9
plt.rcParams["ytick.labelsize"] = 9

fig, ax = plt.subplots(figsize=(8.6, 5.3), dpi=300)
fig.patch.set_facecolor("white")
ax.set_facecolor(SURFACE)
bars = ax.bar(categories, values, color=[PRIMARY, "#0F66D7", ACCENT], edgecolor="white", linewidth=1.0, width=0.58)

ax.set_ylabel('Number of Tickets', color=TEXT)
ax.set_title('Monthly Ticket Summary by Category', color=TEXT, pad=12, fontweight='bold')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color(LIGHT)
ax.spines['bottom'].set_color(LIGHT)
ax.yaxis.grid(True, linestyle='-', alpha=0.85, color=LIGHT)
ax.set_axisbelow(True)
ax.tick_params(colors=MUTED)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 0.12, int(yval), ha='center', va='bottom', color=TEXT, fontsize=9, fontweight='bold')

os.makedirs(os.path.dirname(chart_file_path), exist_ok=True)
plt.tight_layout()
plt.savefig(chart_file_path, dpi=300)
print(f"Chart saved to {chart_file_path}")
    `;
    generateChartNode.setParams({ 
      code: pythonCode,
      requireConfirmation: false
    });
    return shared; // Return shared
  };
  
  // 3. Node to format the final output and write to file
  const formatOutputNode = new AsyncNode();
  formatOutputNode.prepAsync = async (shared) => { // prepAsync receives `shared`
    // Defensive check
    if (typeof shared === 'undefined' || shared === null) {
      console.warn("Zoho Parser: 'shared' object was undefined or null in formatOutputNode.prepAsync, initializing.");
      shared = {};
    }
    if (!shared.total_tickets || !shared.ticket_counts || !shared.chart_path) {
        throw new Error("Zoho Parser: Missing required data in shared object for final output.");
    }

    const jsonOutput = {
      tickets: {
        source: 'Zoho',
        total: shared.total_tickets,
        software_count: shared.ticket_counts.Software,
        hardware_count: shared.ticket_counts.Hardware,
        misc_count: shared.ticket_counts.Miscellaneous,
        chart_path: shared.chart_path
      }
    };
    
    const clientNameSanitized = shared.client_name.replace(/[^a-zA-Z0-9]/g, '_');
    const tempFilePath = path.join(process.cwd(), `temp_zoho_tickets_output_${clientNameSanitized}.json`);

    fs.writeFileSync(tempFilePath, JSON.stringify(jsonOutput, null, 2));
    console.log(`Zoho Parser: Wrote output to temporary file: ${tempFilePath}`);

    shared.output_filepath = tempFilePath; // Store the filepath in shared.output_filepath
    console.log("Zoho Parser: Completed and captured output filepath.");
    return shared; // Return shared
  };

  // Chain the nodes
  flow.start(processCsvNode)
    .next(generateChartNode)
    .next(formatOutputNode);

  return flow;
}
